name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Roda diariamente à meia-noite UTC
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Commit e push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Atualizando Snake Game"
          add: "dist/snake.svg"
          push: true
