name: Generate Snake GIF

on:
  schedule:
    - cron: "0 0 * * *"  # Roda todo dia à meia-noite UTC
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Converter SVG para GIF
        uses: crazy-max/ghaction-gifski@v2
        with:
          input: dist/snake.svg
          output: dist/snake.gif
          width: 800

      - name: Commit e push da animação
        uses: EndBug/add-and-commit@v9
        with:
          message: "Atualizando GIF do Snake Game"
          add: "dist/snake.gif"
          push: true
