name: Generate Snake GIF

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Instalar dependências
        run: sudo apt-get install -y imagemagick librsvg2-bin

      - name: Converter SVG para PNG
        run: |
          rsvg-convert -h 500 -o dist/snake.png dist/snake.svg

      - name: Converter PNG para GIF
        run: |
          convert -delay 10 -loop 0 dist/snake.png dist/snake.gif

      - name: Commit e push da animação
        uses: EndBug/add-and-commit@v9
        with:
          message: "Atualizando GIF do Snake Game"
          add: "dist/snake.gif"
          push: true
