name: Generate Snake GIF

on:
  schedule:
    - cron: "0 0 * * *"  # Roda diariamente à meia-noite UTC
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Instalar ImageMagick
        run: sudo apt-get install -y imagemagick

      - name: Converter SVG para GIF
        run: |
          convert -delay 10 -loop 0 dist/snake.svg dist/snake.gif

      - name: Commit e push da animação
        uses: EndBug/add-and-commit@v9
        with:
          message: "Atualizando GIF do Snake Game"
          add: "dist/snake.gif"
          push: true
